name: Release

on: workflow_dispatch
#on:
#  push:
#    branches:
#      - master
#      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        run: npm run build
      - name: Show secrets
        run: echo "Cur secrets ${{ steps.GITHUB_TOKEN }}"
      - name: Release
        id: release-step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Show
        run: echo "Got version ${{ steps.release-step.outputs.cdn_version }}"
